'use client'

import { useEffect, useState } from 'react'

import { motion } from 'framer-motion'

interface HistoryItem
{
  filename: string

  prediction: string

  confidence: number

  timestamp: string
}

export function HistorySection()
{
  const [history, setHistory] =
    useState<HistoryItem[]>([])

  useEffect(() =>
  {
    fetch(
      'https://banana-backend-eqj6.onrender.com/history'
    )
      .then((res) => res.json())

      .then((data) =>
      {
        const reversed = [
          ...data,
        ].reverse()

        setHistory(reversed)
      })

      .catch((err) =>
        console.error(err)
      )
  }, [])

  const getLabel = (
    prediction: string
  ) =>
  {
    if (
      prediction === 'Overripe'
    )
    {
      return {
        label: 'Overripe',

        color:
          'text-orange-400',

        border:
          'border-orange-400/20',

        bg: 'bg-orange-500/10',
      }
    }

    if (
      prediction === 'Ripe'
    )
    {
      return {
        label: 'Ripe',

        color:
          'text-green-400',

        border:
          'border-green-400/20',

        bg: 'bg-green-500/10',
      }
    }

    return {
      label: 'Unripe',

      color:
        'text-blue-400',

      border:
        'border-blue-400/20',

      bg: 'bg-blue-500/10',
    }
  }

  return (

    <section
      id="history"
      className="relative py-24 overflow-hidden"
    >

      {/* Background */}
      <div className="absolute top-0 left-0 w-96 h-96 bg-yellow-400/5 blur-3xl rounded-full opacity-20" />

      <div className="absolute bottom-0 right-0 w-96 h-96 bg-green-400/5 blur-3xl rounded-full opacity-20" />

      <div className="relative z-10 max-w-7xl mx-auto px-6">

        {/* Heading */}
        <motion.div
          initial={{
            opacity: 0,
            y: 20,
          }}
          whileInView={{
            opacity: 1,
            y: 0,
          }}
          className="text-center mb-16"
        >

          <div className="inline-block mb-4 px-4 py-2 bg-zinc-900 border border-zinc-800 rounded-full">

            <span className="text-yellow-400 text-sm font-semibold">

              Prediction Logs

            </span>

          </div>

          <h2 className="text-4xl md:text-6xl font-bold mb-5">

            Detection History

          </h2>

          <p className="text-zinc-400 text-lg max-w-2xl mx-auto">

            Real-time prediction records generated by the AI detection engine.

          </p>

          {/* CSV Button */}
          <div className="mt-8">

            <a
              href="https://banana-backend-eqj6.onrender.com/export-csv"
              target="_blank"
            >

              <button className="px-7 py-3 rounded-xl bg-yellow-400 text-black font-semibold hover:bg-yellow-300 transition-all duration-300">

                Download CSV Report

              </button>

            </a>

          </div>

        </motion.div>

        {/* Cards */}
        <div className="grid grid-cols-1 md:grid-cols-2 xl:grid-cols-3 gap-8">

          {history
            .slice(0, 6)
            .map(
              (
                item,
                index
              ) =>
              {
                const status =
                  getLabel(
                    item.prediction
                  )

                return (

                  <motion.div
                    key={index}
                    initial={{
                      opacity: 0,
                      y: 20,
                    }}
                    whileInView={{
                      opacity: 1,
                      y: 0,
                    }}
                    transition={{
                      delay:
                        index * 0.05,
                    }}
                    className={`rounded-3xl border ${status.border} ${status.bg} p-6 backdrop-blur-xl hover:-translate-y-2 transition-all duration-500 bg-zinc-900/80`}
                  >

                    <div className="space-y-5">

                      {/* File */}
                      <div>

                        <p className="text-zinc-500 text-sm mb-2">

                          File Name

                        </p>

                        <p className="text-white font-semibold truncate">

                          {item.filename ||
                            'banana-image'}

                        </p>

                      </div>

                      {/* Prediction */}
                      <div>

                        <p className="text-zinc-500 text-sm mb-2">

                          Prediction

                        </p>

                        <p
                          className={`font-bold text-lg ${status.color}`}
                        >

                          {
                            status.label
                          }

                        </p>

                      </div>

                      {/* Confidence */}
                      <div>

                        <div className="flex items-center justify-between mb-2">

                          <p className="text-zinc-500 text-sm">

                            Confidence

                          </p>

                          <p className="text-yellow-400 font-semibold">

                            {Math.round(
                              item.confidence
                            )}
                            %

                          </p>

                        </div>

                        <div className="w-full h-2 bg-zinc-800 rounded-full overflow-hidden">

                          <div
                            className="h-full bg-gradient-to-r from-yellow-400 to-green-400"
                            style={{
                              width: `${item.confidence}%`,
                            }}
                          />

                        </div>

                      </div>

                      {/* Timestamp */}
                      <div>

                        <p className="text-zinc-500 text-sm mb-2">

                          Timestamp

                        </p>

                        <p className="text-zinc-300 text-sm">

                          {item.timestamp
                            ? new Date(
                                item.timestamp
                              ).toLocaleString()
                            : 'Recently'}

                        </p>

                      </div>

                    </div>

                  </motion.div>
                )
              }
            )}

        </div>

      </div>

    </section>
  )
}